apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.13.0
    helm:
      valuesObject:
        expose:
          type: nodePort
          tls:
            enabled: false
        externalURL: http://harbor.local
        harborAdminPassword: "Harbor12345"
        core:
          secret: "coresecretvalue"
        jobservice:
          replicas: 1
          secret: "coresecretvalue"
          strategy:
            type: Recreate
        registry:
          replicas: 1
          strategy:
            type: Recreate
        secretKey: "abcdefgh12345678"
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
